### ISSUE TITLE
Cannot get content of attachment named "[Untitled].pdf"

### ISSUE THREAD

**Issue by mpbelov** [XeroAPI/Xero-Net#206] opened 2016-05-23 09:29 UTC
Hi, please consider the following reprosteps:
1. Create a bill and attach file named "[Untitled].pdf" (without quotes)
2. Execute the following code:

```
            var invoices = apiCore.Invoices
                .Where("InvoiceID = GUID(\"fcb6512c-81aa-49a4-bac6-1359884afcc1\")")
                .Find()
                .ToArray();
            var invoice = invoices.First();
            var attachments = apiCore.Attachments.List(AttachmentEndpointType.Invoices, Guid.Parse("fcb6512c-81aa-49a4-bac6-1359884afcc1"));
            foreach (var a in attachments) {
                var content = apiCore.Attachments.Get(AttachmentEndpointType.Invoices, a.Id, a.FileName);
            }
```

Expected result: contens is recieved without errors
Actual result: UnauthorizedException is thrown with the following message:

> An unhandled exception of type 'Xero.Api.Infrastructure.Exceptions.UnauthorizedException' occurred in Xero.Api.dll
> 
> Additional information: oauth_problem=signature_invalid&oauth_problem_advice=Failed%20to%20validate%20signature

**Comment by MJMortimer** [comment] 2016-06-06 23:56
I am still unable to reproduce this error on the latest versions of the wrapper using the exact code you supplied (with required changes e.g changing the invoice id). Are you still having this issue?

**Comment by mpbelov** [comment] 2016-06-08 10:14
Hi @MJMortimer 

Yes, unfortunately I'm still able to reproduce the issue.

Originally I reproduced it using self compiled source code pulled from git repository. Now I validated it again with nuget package:
1. created new VS project
2. added latest version of Xero-Net wrapper via nuget
3. uploaded my certificate to the Demo company and generated both consumer key and secret.
4. pasted the same code for private authentication you provide on github title page
Here is the complete code copypasted from my program.cs:
```
        static void Main(string[] args) {
            var apiCore = new XeroCoreApi(
                "https://api.xero.com/api.xro/2.0/",
                new PrivateAuthenticator(getCert()),
                new Consumer("6EMPRYU3R0MQZH6OJ0PPWNBCRS9KOL", "BWZDETOHSG67L5XM46EQR7WRMQFBCC"),
                null,
                new DefaultMapper(),
                new DefaultMapper());

            var invoiceId = Guid.Parse("fcb6512c-81aa-49a4-bac6-1359884afcc1");
            var attachments = apiCore.Attachments.List(AttachmentEndpointType.Invoices, invoiceId); // [Untitled].pdf
            foreach (var a in attachments) {
                var content = apiCore.Attachments.Get(AttachmentEndpointType.Invoices, invoiceId, a.FileName);
            }
```
The same error occured. If I change the invoiceId with one that contains "right" named attachment, It will work OK.

I'd suppose this is kind of machine- or private authenticator-related issue, but it's reproducable in our production environment which uses partner authentication. 

I can send you the self-issued certificate, zipped VS project folder, my Xero Demo company id, anything that might help.

**Comment by MJMortimer** [comment] 2017-01-26 01:09
Unfortunately I'm still unable to reproduce this error @mpbelov. It may just be an issue with the environment your system is running in. Considering I cannot reproduce the issue and that no other users are seeing this problem I'm going to close this issue and will reopen it if other users encounter this problem.

**Closed by MJMortimer** 2017-01-26 01:09 UTC
