### ISSUE TITLE
Adding an attachment with optional includeOnline set to true causes a reference null exception

### ISSUE THREAD

**Issue by iberodev** [XeroAPI/Xero-Net#186] opened 2016-03-15 22:13 UTC
I'm using Xero API SDK (Minimal) 2.1.2.7 (but the same happens with 2.0.X previous versions).
When adding an attachment to an existing invoice everything works well with the optional `includeOnline = false` (by default, if omitted is false), but when I set it to true it causes a `NullReferenceException`.

The following line:
`coreApi.Attachments.AddOrReplace(attachment, Xero.Api.Core.Model.Types.AttachmentEndpointType.Invoices, invoiceId, true);`
will cause this:

```
   at Xero.Api.Common.Extensions.Add(NameValueCollection collection, String name, Nullable`1 value)
   at Xero.Api.Core.Endpoints.AttachmentsEndpoint.AddOrReplace(Attachment attachment, AttachmentEndpointType type, Guid parent, Boolean includeOnline)
   at MyApp.Services.XeroService.XeroService.AttachDocuments(Guid userId, IEnumerable`1 attachments, Guid invoiceId) in c:\gitrepos\myApp\MyApp.Services\XeroService\XeroService.cs:line 446
```

The attachment file name has no spaces and it all works well when that parameter is false.
Any advise?

**Comment by MJMortimer** [comment] 2016-04-04 22:48
Hey @realavaloro, I cannot seem to replicate this  issue, were you able to resolve this?

**Comment by realavaloro** [comment] 2016-04-04 23:37
Hi, I couldn't resolve it. It won't accept a false optional parameter as described.

**Comment by realavaloro** [comment] 2016-04-04 23:38
Sorry, I meant a true value optional parameter.  With false it's all good

**Comment by MJMortimer** [comment] 2016-06-07 00:08
Hey @iberodev, is this still an issue? I still cannot reproduce the error, and we have [example tests for this functionality](https://github.com/XeroAPI/Xero-Net/blob/master/CoreTests/Integration/Attachments/Attachments.cs#L70-L92) which also work for me.
Do those tests also fail for you?

**Comment by MJMortimer** [comment] 2017-01-26 01:11
Considering I cannot reproduce the issue and that no other users have reported this problem I'm going to close this issue and will reopen it if other users run into this problem.

**Closed by MJMortimer** 2017-01-26 01:11 UTC
