### ISSUE TITLE
I am implementing asp web forms and getting a endless loop

### ISSUE THREAD

**Issue by henzard** [XeroAPI/Xero-Net#130] opened 2015-11-12 00:20 UTC
I am using the PublicAuthenticator. When var authorizeUrl = GetAuthorizeUrl(token); I should get the token and not trigger the authorizeUrl again but the systems does not create a token.

**Comment by MJMortimer** [comment] 2015-12-01 22:20
Hey @henzard, 

If so, are you able to give us more details on the issue is?

Cheers,
Matt

**Comment by philals** [comment] 2016-02-10 21:19
Closed as no movement

**Closed by philals** 2016-02-10 21:19 UTC
